### ISSUE TITLE
The SteamWorks API call   ORG.SHIRAKUMO.FRAF.STEAMWORKS.CFFI::CREATE-INTERFACE did not succeed for an unknown reason

### ISSUE THREAD

**Issue by gregcman** [Shinmera/cl-steamworks#2]
It seems that App is being set up, because Steam prints `Starting App 480` and `Exiting App 480`.

This is the output when running `(cl-steamworks-generator:setup)`, it mentions something about `no libffi` although libffi is installed.
https://gist.github.com/gregcman/01c529429f2967ec40610d2b491ca53f#file-setup-repl-lisp

This is the output when setting up the client https://gist.github.com/gregcman/01c529429f2967ec40610d2b491ca53f#file-client-repl-lisp , which raises the error.

This is what Steam prints when run from the command line: https://gist.github.com/gregcman/01c529429f2967ec40610d2b491ca53f#file-steam-stdout-md , while setting up the client.

**Comment by Shinmera** [comment]
Is this still the case with the latest commit and SDK? (1.48)

**Comment by gregcman** [comment]
With the latest cl-steamworks and SDK there seem to be no errors AFAIK. I can start and stop an app repeatedly with no error messages.
```(make-instance 'cl-steamworks:steamworks-client :app-id 480)```
and
```(cl-steamworks:free (cl-steamworks:steamworks))```
seem to work in different combinations.

**Comment by Shinmera** [comment]
Fantastic! I'll close this issue then.
